upstream softmusic_api {
    server api:8080;
    keepalive 32;
}

upstream softmusic_web {
    server web:80;
    keepalive 32;
}

upstream softmusic_lp {
    server lp:80;
    keepalive 16;
}

upstream softmusic_admin {
    server admin-web:80;
    keepalive 16;
}

upstream softmusic_grafana {
    server grafana:3000;
    keepalive 8;
}
