import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("health", "routes/health.tsx"),
  route("health/live", "routes/health.live.tsx"),
  route("health/ready", "routes/health.ready.tsx"),
  route("metrics", "routes/metrics.tsx"),
  route("auth/register", "routes/auth.register.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/forgot-password", "routes/auth.forgot-password.tsx"),
  route("auth/verify-reset-code", "routes/auth.verify-reset-code.tsx"),
  route("auth/reset-password", "routes/auth.reset-password.tsx"),
  route("auth/refresh", "routes/auth.refresh.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("auth/me", "routes/auth.me.tsx"),
  route("bands", "routes/bands._index.tsx"),
  route("bands/:bandId/invites", "routes/bands.$bandId.invites.tsx"),
  route("bands/:bandId/roles", "routes/bands.$bandId.roles._index.tsx"),
  route("bands/:bandId/roles/:roleId", "routes/bands.$bandId.roles.$roleId.tsx"),
  route("bands/:bandId/members", "routes/bands.$bandId.members._index.tsx"),
  route("bands/:bandId/members/:memberId", "routes/bands.$bandId.members.$memberId.tsx"),
  route("bands/:bandId/plan", "routes/bands.$bandId.plan.tsx"),
  route("bands/:bandId/addresses", "routes/bands.$bandId.addresses._index.tsx"),
  route("bands/:bandId/addresses/:addressId", "routes/bands.$bandId.addresses.$addressId.tsx"),
  route("bands/:bandId/schedules", "routes/bands.$bandId.schedules._index.tsx"),
  route(
    "bands/:bandId/schedules/occurrences/:occurrenceId/cancel",
    "routes/bands.$bandId.schedules.occurrences.$occurrenceId.cancel.tsx",
  ),
  route(
    "bands/:bandId/schedules/occurrences/:occurrenceId",
    "routes/bands.$bandId.schedules.occurrences.$occurrenceId.tsx",
  ),
  route("bands/:bandId/schedules/:scheduleId", "routes/bands.$bandId.schedules.$scheduleId.tsx"),
  route("schedule/upcoming", "routes/schedule.upcoming.tsx"),
  route("schedule/mine", "routes/schedule.mine.tsx"),
  route("geo/autocomplete", "routes/geo.autocomplete.tsx"),
  route("invites/pending", "routes/invites.pending.tsx"),
  route("invites/preview", "routes/invites.preview.tsx"),
  route("invites/accept", "routes/invites.accept.tsx"),
  route("invites/decline", "routes/invites.decline.tsx"),
  route("billing/invoices", "routes/billing.invoices.tsx"),
  route("billing/invoices/:invoiceId", "routes/billing.invoices.$invoiceId.tsx"),
  route("billing/invoices/:invoiceId/pay", "routes/billing.invoices.$invoiceId.pay.tsx"),
  route("billing/invoices/:invoiceId/refresh", "routes/billing.invoices.$invoiceId.refresh.tsx"),
  route("billing/status", "routes/billing.status.tsx"),
  route("billing/checkout", "routes/billing.checkout.tsx"),
  route("webhooks/asaas", "routes/webhooks.asaas.tsx"),
  route("admin/auth/login", "routes/admin.auth.login.tsx"),
  route("admin/me", "routes/admin.me.tsx"),
  route("admin/admins", "routes/admin.admins._index.tsx"),
  route("admin/admins/:adminId", "routes/admin.admins.$adminId.tsx"),
  route("admin/admins/:adminId/reset-password", "routes/admin.admins.$adminId.reset-password.tsx"),
  route("admin/sales/register", "routes/admin.sales.register.tsx"),
  route("admin/dashboard/stats", "routes/admin.dashboard.stats.tsx"),
  route("admin/users", "routes/admin.users.tsx"),
  route("admin/bands", "routes/admin.bands.tsx"),
  route("admin/bands/:bandId/exempt", "routes/admin.bands.$bandId.exempt.tsx"),
  route("admin/bands/:bandId/suspend", "routes/admin.bands.$bandId.suspend.tsx"),
  route("admin/songs/block", "routes/admin.songs.block.tsx"),
  route("admin/marketing/send", "routes/admin.marketing.send.tsx"),
  route("admin/billing/suspend-overdue", "routes/admin.billing.suspend-overdue.tsx"),
  route("admin/billing/settings", "routes/admin.billing.settings.tsx"),
  route("admin/billing/invoices", "routes/admin.billing.invoices.tsx"),
  route(
    "admin/billing/invoices/:invoiceId/payment-link",
    "routes/admin.billing.invoices.$invoiceId.payment-link.tsx",
  ),
  route("dashboard/stats", "routes/dashboard.stats.tsx"),
  route("songs/analyze", "routes/songs.analyze.tsx"),
  route("songs/upload", "routes/songs.upload.tsx"),
  route("songs/cifra-draft", "routes/songs.cifra-draft.tsx"),
  route("songs/global", "routes/songs.global.tsx"),
  route("songs", "routes/songs._index.tsx"),
  route("songs/:songId/link", "routes/songs.$songId.link.tsx"),
  route("songs/:songId/share", "routes/songs.$songId.share.tsx"),
  route("songs/:songId/unshare", "routes/songs.$songId.unshare.tsx"),
  route("songs/:songId/analyze-audio-upload", "routes/songs.$songId.analyze-audio-upload.tsx"),
  route("songs/:songId/analyze-audio", "routes/songs.$songId.analyze-audio.tsx"),
  route("songs/:songId", "routes/songs.$songId.tsx"),
  route("songs/:songId/cancel", "routes/songs.$songId.cancel.tsx"),
  route("songs/:songId/job", "routes/songs.$songId.job.tsx"),
  route("songs/:songId/analysis", "routes/songs.$songId.analysis.tsx"),
  route("songs/:songId/timeline", "routes/songs.$songId.timeline.tsx"),
  route("songs/:songId/chords", "routes/songs.$songId.chords.tsx"),
  route("songs/:songId/cifra-variations", "routes/songs.$songId.cifra-variations.tsx"),
  route(
    "songs/:songId/cifra-variations/:variationId",
    "routes/songs.$songId.cifra-variations.$variationId.tsx",
  ),
  route("songs/:songId/lyrics", "routes/songs.$songId.lyrics.tsx"),
  route("songs/:songId/waveform", "routes/songs.$songId.waveform.tsx"),
  route("songs/:songId/audio", "routes/songs.$songId.audio.tsx"),
  route("songs/:songId/stems", "routes/songs.$songId.stems.tsx"),
  route("songs/:songId/stems/:stemName/audio", "routes/songs.$songId.stems.$stemName.audio.tsx"),
  route("jobs/:jobId", "routes/jobs.$jobId.tsx"),
] satisfies RouteConfig;
