import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("health", "routes/health.tsx"),
  route("health/live", "routes/health.live.tsx"),
  route("health/ready", "routes/health.ready.tsx"),
  route("metrics", "routes/metrics.tsx"),
  route("auth/register", "routes/auth.register.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/refresh", "routes/auth.refresh.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("auth/me", "routes/auth.me.tsx"),
  route("bands", "routes/bands._index.tsx"),
  route("bands/:bandId/invites", "routes/bands.$bandId.invites.tsx"),
  route("invites/accept", "routes/invites.accept.tsx"),
  route("billing/invoices", "routes/billing.invoices.tsx"),
  route("billing/status", "routes/billing.status.tsx"),
  route("billing/checkout", "routes/billing.checkout.tsx"),
  route("webhooks/asaas", "routes/webhooks.asaas.tsx"),
  route("admin/auth/login", "routes/admin.auth.login.tsx"),
  route("admin/users", "routes/admin.users.tsx"),
  route("admin/bands", "routes/admin.bands.tsx"),
  route("admin/bands/:bandId/exempt", "routes/admin.bands.$bandId.exempt.tsx"),
  route("admin/bands/:bandId/suspend", "routes/admin.bands.$bandId.suspend.tsx"),
  route("admin/songs/block", "routes/admin.songs.block.tsx"),
  route("admin/marketing/send", "routes/admin.marketing.send.tsx"),
  route("admin/billing/suspend-overdue", "routes/admin.billing.suspend-overdue.tsx"),
  route("dashboard/stats", "routes/dashboard.stats.tsx"),
  route("songs/analyze", "routes/songs.analyze.tsx"),
  route("songs/upload", "routes/songs.upload.tsx"),
  route("songs/global", "routes/songs.global.tsx"),
  route("songs", "routes/songs._index.tsx"),
  route("songs/:songId/link", "routes/songs.$songId.link.tsx"),
  route("songs/:songId", "routes/songs.$songId.tsx"),
  route("songs/:songId/cancel", "routes/songs.$songId.cancel.tsx"),
  route("songs/:songId/job", "routes/songs.$songId.job.tsx"),
  route("songs/:songId/analysis", "routes/songs.$songId.analysis.tsx"),
  route("songs/:songId/timeline", "routes/songs.$songId.timeline.tsx"),
  route("songs/:songId/chords", "routes/songs.$songId.chords.tsx"),
  route("songs/:songId/cifra-variations", "routes/songs.$songId.cifra-variations.tsx"),
  route("songs/:songId/lyrics", "routes/songs.$songId.lyrics.tsx"),
  route("songs/:songId/waveform", "routes/songs.$songId.waveform.tsx"),
  route("songs/:songId/audio", "routes/songs.$songId.audio.tsx"),
  route("songs/:songId/stems", "routes/songs.$songId.stems.tsx"),
  route("songs/:songId/stems/:stemName/audio", "routes/songs.$songId.stems.$stemName.audio.tsx"),
  route("jobs/:jobId", "routes/jobs.$jobId.tsx"),
] satisfies RouteConfig;
